### ISSUE TITLE
fix version in action step "Update package.json version"

### ISSUE THREAD

**Issue by cachechaser** [pyditn2/Pyditn-s-Dice-Thrower-Pro#19]
Should also update Cargo.toml (apparently worked until v0.1.14) and tauri.conf.json (source of release being v1.0.0 in assets) instead of package.json only.

As mentioned in https://github.com/tauri-apps/tauri/discussions/6347 remove version in tauri.conf.json 

OR

```yaml
      - name: Update versions in files
        run: |
          npm version ${{ steps.version.outputs.version }} --no-git-tag-version
          
          # replaces version in Cargo.toml with steps.version.outputs.version in-place
          sed -i 's/^version = "[0-9.]*"/version = "${{ steps.version.outputs.version }}"/' src-tauri/Cargo.toml
          
          # replaces version in tauri.conf.json in-place (BUT should use a JSON-safe method with jq instead)
          sed -i 's/"version": "[^"]*"/"version": "${{ steps.version.outputs.version }}"/' src-tauri/tauri.conf.json
```
